name: olyTPx
main: com.olympuspvp.tp.olyTP
version: 1.1
author: willno123
description: Admin teleport

commands:
    tp:
        description: Teleports
    back:
        description: Teleports players back to their previous location